### ISSUE TITLE
no longer works with budgie

### ISSUE THREAD

**Issue by solomongrundy6** [solus-packages/xpad#1]
Now that budgie has migrated to StatusNotifier, xpad no longer works as intended (since it stays in the system tray but uses XEMBED).  The correct fix would be for xpad to migrate to use StatusNotifier, but since it was last updated in 2009 that seems unlikely.  

A workaround is to pin it to your icon tasklist instead, and change its shortcut to "xpad -t" instead of just "xpad" - this will have it copy the main action that the tray icon had when left-clicked - toggle the visibility of your pads on and off.  But this requires you to have the "use system tray" option enabled, which is counter-intuitive if it doesn't appear in the tray.  You also cannot reach certain non-critical things in the menu that the tray icon would normally have, it seems.

I don't know if removing it from the repository completely is necessarily warranted, since it would still work as normal in other DEs that still support XEMBED, but I wanted to file an issue so that it was known about.

**Comment by algent-al** [comment]
Hi @solomongrundy6!
The proper place to report the issues is here. https://github.com/getsolus/packages/issues/new/choose
